[build]
  command = "npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["@node-rs/helper"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"